language: node_js

node_js:
  - 8

cache:
  yarn: true
  directories:
    - node_modules

notifications:
  email: false
  webhooks:
    urls:
      - https://zulip.org/zulipbot/travis
    on_success: always
    on_failure: always

install:
  npm i yarn -g
  yarn

scripts:
  - npm run test:lint
  - npm run test:flow
  - npm run test:coveralls

env:
  - COVERALLS_REPO_TOKEN=4eYQDtWoBJlDz2QkxoQ2UcnmJFcOB7zkv
